'use strict';
const $=id=>document.getElementById(id),dbName='ganado-offline-v1';let db,animals={},records=[];
function request(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function start(){db=await new Promise((res,rej)=>{let r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore('settings');d.createObjectStore('records',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});$('date').value=new Date().toLocaleDateString('en-CA');$('url').value=await get('url')||'';$('key').value=await get('key')||'';animals=await get('animals')||{};await refresh();navigator.serviceWorker?.register('./sw.js').catch(()=>{});updateOnline()}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
async function get(k){return request(store('settings').get(k))}
async function set(k,v){return request(store('settings','readwrite').put(v,k))}
async function refresh(){records=await request(store('records').getAll());$('pending').textContent=records.filter(r=>!r.synced).length;$('known').textContent=Object.keys(animals).length;let rows=records.filter(r=>r.fecha===$('date').value),known=rows.filter(r=>r.gain!==null),gain=known.reduce((a,r)=>a+r.gain,0),avg=known.filter(r=>r.days>0);$('summary').innerHTML=`<div class="stat"><span>Registrados</span><b>${rows.length}</b></div><div class="stat"><span>Con ganancia calculable</span><b>${known.length}</b></div><div class="stat"><span>Kilos ganados</span><b>${gain.toFixed(1)} kg</b></div><div class="stat"><span>Promedio gramos/día</span><b>${avg.length?(avg.reduce((a,r)=>a+r.gain*1000/r.days,0)/avg.length).toFixed(0):'—'}</b></div>`;showAnimal()}
function norm(s){return String(s||'').trim().replace(/\.0$/,'').toUpperCase()}
function lastFor(tag,date){let a=animals[tag];let h=(a?.history||[]).map(x=>({fecha:x.fecha,peso:x.peso}));for(let r of records)if(r.arete===tag&&r.fecha<date)h.push({fecha:r.fecha,peso:r.peso});return h.filter(x=>x.fecha<date).sort((a,b)=>b.fecha.localeCompare(a.fecha))[0]||null}
function daysBetween(a,b){return Math.round((Date.parse(b+'T12:00:00')-Date.parse(a+'T12:00:00'))/86400000)}
function showAnimal(){let tag=norm($('tag').value),a=animals[tag],p=lastFor(tag,$('date').value);$('animal').textContent=!tag?'Escribe un arete para consultar el último peso.':!a?'⚠️ Arete desconocido: se registrará para revisión.':a.duplicate?'⚠️ Arete repetido en inventario.':`Lote: ${a.lote||'sin lote'} · Último peso: ${p?p.peso+' kg ('+p.fecha+')':'sin pesaje previo'}`}
async function save(){let arete=norm($('tag').value),peso=Number($('weight').value),fecha=$('date').value;if(!arete||!fecha||!Number.isFinite(peso)||peso<=0||!$('weight').value){alert('Ingresa arete, fecha y peso válido.');return}if(records.some(r=>r.arete===arete&&r.fecha===fecha)){alert('Ese arete ya está registrado en esta fecha.');return}let prev=lastFor(arete,fecha),days=prev?daysBetween(prev.fecha,fecha):null;if(days!==null&&days<=0){alert('La fecha debe ser posterior al último pesaje.');return}let row={id:crypto.randomUUID(),arete,peso,fecha,gain:prev?peso-prev.peso:null,days,lote:animals[arete]?.lote||'',synced:false};await request(store('records','readwrite').add(row));$('tag').value='';$('weight').value='';await refresh();$('tag').focus()}
function updateOnline(){$('online').textContent=navigator.onLine?'Con Internet':'Sin Internet'}
function config(){let url=$('url').value.trim(),key=$('key').value.trim();if(!/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/.test(url)||!key)throw Error('Configura la URL /exec y la clave.');return {url,key}}
function jsonp(url,params){return new Promise((resolve,reject)=>{let cb='cb_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>finish(new Error('Tiempo agotado')),25000);function finish(err,data){clearTimeout(timer);s.remove();delete window[cb];err?reject(err):resolve(data)}window[cb]=data=>finish(null,data);s.onerror=()=>finish(new Error('No se pudo contactar al servidor'));s.src=url+'?'+new URLSearchParams({...params,callback:cb});document.head.append(s)})}
async function download(){try{let {url,key}=config();$('message').textContent='Descargando inventario...';let r=await jsonp(url,{action:'inventory',key});if(!r.ok)throw Error(r.error);animals=r.animals;await set('animals',animals);await set('url',url);await set('key',key);await refresh();$('message').textContent='Inventario descargado. Ya puedes pesar sin Internet.'}catch(e){$('message').textContent='Error: '+e.message}}
async function sync(){try{let {url,key}=config();if(!navigator.onLine)throw Error('No hay conexión');await set('url',url);await set('key',key);let pending=records.filter(r=>!r.synced);if(!pending.length){$('message').textContent='No hay registros pendientes.';return}for(let i=0;i<pending.length;i+=20){let batch=pending.slice(i,i+20);$('message').textContent=`Enviando ${Math.min(i+20,pending.length)}/${pending.length}...`;let body=new URLSearchParams({key,batch:JSON.stringify(batch)});await fetch(url,{method:'POST',mode:'no-cors',body});let verified=[];for(let attempt=0;attempt<3;attempt++){let result=await jsonp(url,{action:'status',key,ids:batch.map(r=>r.id).join(',')});if(!result.ok)throw Error(result.error);verified=result.ids;if(verified.length===batch.length)break;await new Promise(r=>setTimeout(r,1200))}for(let r of batch)if(verified.includes(r.id)){r.synced=true;await request(store('records','readwrite').put(r))}if(verified.length!==batch.length)throw Error('Algunos registros no fueron confirmados. No se borraron: reintenta sincronizar.')}await refresh();$('message').textContent='Sincronización verificada. Registros guardados en Google Sheets.'}catch(e){$('message').textContent='Error: '+e.message+'\nLos registros locales se conservan.'}}
function csv(){let rows=[['ID','Fecha','Arete','Peso kg','Ganancia kg','Días','Lote','Sincronizado'],...records.map(r=>[r.id,r.fecha,r.arete,r.peso,r.gain??'',r.days??'',r.lote,r.synced?'Sí':'No'])];let data='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');let link=document.createElement('a'),blob=new Blob([data],{type:'text/csv;charset=utf-8'});link.href=URL.createObjectURL(blob);link.download='respaldo_pesajes_'+new Date().toISOString().slice(0,10)+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),3000)}
$('save').onclick=save;$('download').onclick=download;$('sync').onclick=sync;$('backup').onclick=csv;$('tag').oninput=showAnimal;$('date').onchange=refresh;addEventListener('online',updateOnline);addEventListener('offline',updateOnline);start().catch(e=>alert('No se pudo iniciar almacenamiento local: '+e.message));
